
// Test markdown content from ai_docs/eg.md (simplified for testing)
export const testMarkdown = `# ORGANIZATIONS & TEAMS
\`\`\`
└── ORGANIZATIONS
    ├── BUYER: Nykaa
    │   ├── Team: SupplyChainTeam [Buyer, ProjectManager] (Planning, order management, and vendor coordination)
    │   ├── Team: SupplyChainHead [Buyer, ProjectManager] (Plan approval and strategic decisions)
    │   └── Team: Finance [Buyer, Finance] (Invoice processing and payment)
    ├── SELLER: ManufacturingVendors
    │   ├── Team: OrderManagement [Seller, ProjectManager] (PO acknowledgment and ASN management)
    │   ├── Team: Production [Seller, QualityAssurance] (Manufacturing and quality control)
    │   ├── Team: Logistics [Seller, Logistics] (Dispatch and shipping)
    │   └── Team: Accounting [Seller, Finance] (Invoice generation and reconciliation)
\`\`\`

# WORKFLOW HIERARCHY

\`\`\`
Workflow: Private Label Planning {CommerceState} (SKU Level Planning)

  PurchaseReq "Monthly SKU Planning" {CommerceState}
    [Access: BUYER.SupplyChainTeam (RW), BUYER.SupplyChainHead (RW)]
    └── PlanCreation: [DataUpload, BrandLabelMapping, ReviewReady]
        [Access: BUYER.SupplyChainTeam (RW), BUYER.SupplyChainHead (RO)]
    └── PlanApproval: [Submitted, UnderReview, Approved]
        [Access: BUYER.SupplyChainTeam (RO), BUYER.SupplyChainHead (RW)]

Workflow: Manufacturing Purchase Management {CommerceState} (Vendor Order Processing)

  Orders "Purchase Orders" {CommerceState}
    [Access: BUYER.SupplyChainTeam (RW), SELLER.OrderManagement (RO)]
    └── Creation: [PlanImport, VendorAssignment, POGeneration]
        [Access: BUYER.SupplyChainTeam (RW)]
    └── Acknowledgment: [Received, Reviewed, ASNEstimatesProvided]
        [Access: BUYER.SupplyChainTeam (RO), SELLER.OrderManagement (RW)]

  → POAmendment {NonCommerceState}
    [Access: BUYER.SupplyChainTeam (RW), SELLER.OrderManagement (RO)]
    └── Amendment: [AutoGenerated, UnderReview, Approved]
        [Access: BUYER.SupplyChainTeam (RW), SELLER.OrderManagement (RO)]

  → Dispatch {NonCommerceState}
    [Access: SELLER.Logistics (RW), BUYER.SupplyChainTeam (RO)]
    └── Processing: [PreparationInProgress, ReadyForDispatch, DispatchIntimationUploaded]
        [Access: SELLER.Logistics (RW), BUYER.SupplyChainTeam (RO)]

Workflow: Order Billing {CommerceState} (Invoice Processing)

  Invoice "Purchase Invoices" {CommerceState}
    [Access: SELLER.Accounting (RW), BUYER.Finance (RO), BUYER.SupplyChainTeam (RO)]
    └── Generation: [DataPreparation, POMatching, FinalReview]
        [Access: SELLER.Accounting (RW)]
    └── Processing: [Submitted, Validated, Accepted]
        [Access: SELLER.Accounting (RO), BUYER.Finance (RW), BUYER.SupplyChainTeam (RO)]
\`\`\`

**WORKFLOW VALIDATION CHECKLIST**:
✓ All workflows start with a Commerce State
✓ Commerce State transition sequence is maintained strictly
✓ Organization structure includes mandatory BUYER and SELLER
✓ Every team has clearly defined roles and business purpose
✓ Access controls are specified at every level
✓ State transitions follow logical business sequence
✓ SubStates and MicroStates add clear business value
✓ RBAC enables proper document flow between organizations
✓ Workflow names reflect actual business processes

This workflow hierarchy maps Nykaa's private label outsource manufacturing process following the universal commerce pattern, with clear organization structure, role definitions, and access controls. The workflow captures the planning approval process, purchase order management with amendment handling for exceptions, dispatch tracking, and invoice processing as described in the business requirements.`;
