import React, { useState } from "react";
import {
  ReactFlow,
  useNodesState,
  useEdgesState,
  MiniMap,
  Controls,
  Background,
  applyNodeChanges,
} from "@xyflow/react";
import "@xyflow/react/dist/style.css";
import ChatPage from "./Chatpage";
import { FlexLayout } from "../components/atoms/layouts";
import { Tab } from "../components/atoms/navigation";
import { Button } from "../components/atoms/form";
import { Select } from "../components/atoms/form";
import MarkdownRenderer from "../utils/MarkdownRenderer";
import { stateMachineExampleDummyData } from "../utils/stateMachine";
import AIConfiguration from "./AIConfiguration";
import WorkflowPreview from "./WorkflowPreview";

const nodeColor = (node: any) => {
  switch (node.type) {
    case "addableNode":
      return "#6ede87";
    case "editableNode":
      return "#6865A5";
    case "accordionNode":
      return "#6ede87";
    default:
      return "#ff0072";
  }
};

const positions = {
  defaultX: 50,
  defaultOffsetX: 350,
  defaultY: 100,
  defaultOffsetY: 100,
};

interface SubState {
  Start?: boolean;
  End?: boolean;
  NextState?: string;
  Owner?: string[];
  Visibility?: Record<string, boolean>;
  Rule?: any;
  MicroStates?: Record<string, {
    Start?: boolean;
    End?: boolean;
    NextState?: string;
    Owner?: string[];
    Desc?: string;
  }>;
}

interface State {
  Schema?: string;
  Props?: {
    Flip?: boolean;
    Edit?: boolean;
    diff?: {
      from?: string;
      to?: string;
    };
  } | null;
  SubStates?: Record<string, SubState>;
  NextState?: string;
  End?: boolean;
  Desc?: string;
  Owner?: string[];
  Visibility?: Record<string, boolean>;
  AttachStates?: string[];
}

interface StateMachine {
  _id?: string;
  AppType?: string;
  Base_sm?: string;
  Branch?: boolean;
  Category?: string;
  Desc?: string;
  ExchangeParamID?: Array<{
    paramID: string;
    publicKey: string;
  }>;
  Index?: number;
  Name: string;
  Organizations?: Array<{
    Name: string;
    Desc: string;
    Teams: Array<{
      Role: string;
      Desc: string;
    }>;
  }>;
  Props?: {
    Icon?: number;
    BgColor?: string;
    Category?: string;
  };
  Roles?: string[];
  StartAt: string;
  Start_sm?: string;
  States: Record<string, State>;
  installed?: number;
  orgParamID?: string;
  smID?: string;
}

interface AnnotationNode {
  id: string;
  type: string;
  draggable: boolean;
  selectable: boolean;
  data: { label: string };
  position: { x: number; y: number };
  parentId?: string;
}

// Test markdown content from ai_docs/eg.md (simplified for testing)
export const testMarkdown = `# ORGANIZATIONS & TEAMS
\`\`\`
└── ORGANIZATIONS
    ├── BUYER: Nykaa
    │   ├── Team: SupplyChainTeam [Buyer, ProjectManager] (Planning, order management, and vendor coordination)
    │   ├── Team: SupplyChainHead [Buyer, ProjectManager] (Plan approval and strategic decisions)
    │   └── Team: Finance [Buyer, Finance] (Invoice processing and payment)
    ├── SELLER: ManufacturingVendors
    │   ├── Team: OrderManagement [Seller, ProjectManager] (PO acknowledgment and ASN management)
    │   ├── Team: Production [Seller, QualityAssurance] (Manufacturing and quality control)
    │   ├── Team: Logistics [Seller, Logistics] (Dispatch and shipping)
    │   └── Team: Accounting [Seller, Finance] (Invoice generation and reconciliation)
\`\`\`

# WORKFLOW HIERARCHY

\`\`\`
Workflow: Private Label Planning {CommerceState} (SKU Level Planning)

  PurchaseReq "Monthly SKU Planning" {CommerceState}
    [Access: BUYER.SupplyChainTeam (RW), BUYER.SupplyChainHead (RW)]
    └── PlanCreation: [DataUpload, BrandLabelMapping, ReviewReady]
        [Access: BUYER.SupplyChainTeam (RW), BUYER.SupplyChainHead (RO)]
    └── PlanApproval: [Submitted, UnderReview, Approved]
        [Access: BUYER.SupplyChainTeam (RO), BUYER.SupplyChainHead (RW)]

Workflow: Manufacturing Purchase Management {CommerceState} (Vendor Order Processing)

  Orders "Purchase Orders" {CommerceState}
    [Access: BUYER.SupplyChainTeam (RW), SELLER.OrderManagement (RO)]
    └── Creation: [PlanImport, VendorAssignment, POGeneration]
        [Access: BUYER.SupplyChainTeam (RW)]
    └── Acknowledgment: [Received, Reviewed, ASNEstimatesProvided]
        [Access: BUYER.SupplyChainTeam (RO), SELLER.OrderManagement (RW)]

  → POAmendment {NonCommerceState}
    [Access: BUYER.SupplyChainTeam (RW), SELLER.OrderManagement (RO)]
    └── Amendment: [AutoGenerated, UnderReview, Approved]
        [Access: BUYER.SupplyChainTeam (RW), SELLER.OrderManagement (RO)]

  → Dispatch {NonCommerceState}
    [Access: SELLER.Logistics (RW), BUYER.SupplyChainTeam (RO)]
    └── Processing: [PreparationInProgress, ReadyForDispatch, DispatchIntimationUploaded]
        [Access: SELLER.Logistics (RW), BUYER.SupplyChainTeam (RO)]

Workflow: Order Billing {CommerceState} (Invoice Processing)

  Invoice "Purchase Invoices" {CommerceState}
    [Access: SELLER.Accounting (RW), BUYER.Finance (RO), BUYER.SupplyChainTeam (RO)]
    └── Generation: [DataPreparation, POMatching, FinalReview]
        [Access: SELLER.Accounting (RW)]
    └── Processing: [Submitted, Validated, Accepted]
        [Access: SELLER.Accounting (RO), BUYER.Finance (RW), BUYER.SupplyChainTeam (RO)]
\`\`\`

**WORKFLOW VALIDATION CHECKLIST**:
✓ All workflows start with a Commerce State
✓ Commerce State transition sequence is maintained strictly
✓ Organization structure includes mandatory BUYER and SELLER
✓ Every team has clearly defined roles and business purpose
✓ Access controls are specified at every level
✓ State transitions follow logical business sequence
✓ SubStates and MicroStates add clear business value
✓ RBAC enables proper document flow between organizations
✓ Workflow names reflect actual business processes

This workflow hierarchy maps Nykaa's private label outsource manufacturing process following the universal commerce pattern, with clear organization structure, role definitions, and access controls. The workflow captures the planning approval process, purchase order management with amendment handling for exceptions, dispatch tracking, and invoice processing as described in the business requirements.`;

const ProjectPlanScreen: React.FC = () => {
  const [activeProjectTab, setActiveProjectTab] = useState("brd");
  const [selectedVersion, setSelectedVersion] = useState("1.0");

  const projectTabItems = [
    {
      id: "brd",
      label: "BRD",
    },
    {
      id: "plan",
      label: "Plan",
    },
    {
      id: "smart-ai",
      label: "Smart AI",
    },
    {
      id: "preview",
      label: "Preview",
    },
  ];

  const CustomMiniMap = (props: any) => {
    setTimeout(() => {
      const titleElement = document.getElementById(
        "react-flow__minimap-desc-1"
      );
      if (titleElement) {
        titleElement.textContent = "Minimap"; // Change the hover text
      }
    }, 5);

    return <MiniMap {...props} />;
  };

  const getNodes = (): AnnotationNode[] => {
    const data: Record<string, StateMachine> = stateMachineExampleDummyData;
    const nodes: AnnotationNode[] = [];
    
    if (!data || Object.keys(data).length === 0) {
      return nodes;
    }

    // Add root node
    nodes.push({
      id: "project-plan-node",
      type: "annotation",
      draggable: false,
      selectable: false,
      data: {
        label: "Project Plan Node",
      },
      position: { x: 100, y: 20 },
      parentId: "",
    });

    // Process by Index (1, 2, 3, ...)
    let currentIndex = 1;
    let foundStateMachine = true;

    while (foundStateMachine) {
      foundStateMachine = false;

      // Find the state machine with current index
      for (const [key, stateMachine] of Object.entries(data)) {
        if (stateMachine?.Index === currentIndex) {
          foundStateMachine = true;

          // Create main node for this state machine
          const mainNode: AnnotationNode = {
            id: `${stateMachine.Name}-node`,
            type: "annotation",
            draggable: false,
            selectable: false,
            data: {
              label: stateMachine.Name,
            },
            position: { x: 100, y: 20 },
            parentId: "project-plan-node",
          };
          nodes.push(mainNode);

          // Process the StartAt state
          const startStateName = stateMachine.StartAt;
          if (startStateName && stateMachine.States[startStateName]) {
            processState(stateMachine, startStateName, stateMachine.Name, nodes);
          }
          break;
        }
      }
      currentIndex++;
    }

    return nodes;
  };

  // Helper function to process a state and its chain
  const processState = (
    stateMachine: StateMachine,
    stateName: string,
    parentId: string,
    nodes: AnnotationNode[]
  ): void => {
    const state = stateMachine.States[stateName];
    if (!state) return;

    // Check schema condition
    const hasCommerceSchema = state.Schema?.includes("Commerce");
    const shouldSkip = hasCommerceSchema && state.Props?.Flip === true;

    if (shouldSkip) {
      return;
    }

    // Create state node
    const stateNode: AnnotationNode = {
      id: stateName,
      type: "annotation",
      draggable: false,
      selectable: false,
      data: {
        label: stateName,
      },
      position: { x: 100, y: 20 },
      parentId: parentId,
    };
    nodes.push(stateNode);

    // Process substates if they exist
    if (state.SubStates && Object.keys(state.SubStates).length > 0) {
      // Find the starting substate
      for (const [subStateName, subState] of Object.entries(state.SubStates)) {
        if (subState.Start) {
          processSubStateChain(state.SubStates, subStateName, stateName, nodes);
          break;
        }
      }
    }

    // Process next state in the chain
    if (state.NextState && stateMachine.States[state.NextState]) {
      processState(stateMachine, state.NextState, parentId, nodes);
    }
  };

  // Helper function to process substate chain
  const processSubStateChain = (
    subStates: Record<string, SubState>,
    currentSubStateName: string,
    parentStateId: string,
    nodes: AnnotationNode[]
  ): void => {
    let currentSubState = subStates[currentSubStateName];
    let currentName = currentSubStateName;

    while (currentSubState && currentName) {
      // Create substate node
      const subStateNode: AnnotationNode = {
        id: currentName,
        type: "annotation",
        draggable: false,
        selectable: false,
        data: {
          label: currentName,
        },
        position: { x: 100, y: 20 },
        parentId: parentStateId,
      };
      nodes.push(subStateNode);

      // Stop if this is an end state
      if (currentSubState.End) {
        break;
      }

      // Move to next substate
      const nextSubStateName = currentSubState.NextState;
      if (nextSubStateName && subStates[nextSubStateName]) {
        currentName = nextSubStateName;
        currentSubState = subStates[nextSubStateName];
      } else {
        break;
      }
    }
  };

  const renderContent = () => {
    switch (activeProjectTab) {
      case "brd":
        return <MarkdownRenderer content={testMarkdown} className="w-full" />;
      case "plan":
        return (
          <div
            className={`flow-builder`}
            id="reactflow-container"
            style={{ touchAction: "none", outline: "none" }}
          >
            <ReactFlow className="reactflow">
              <CustomMiniMap
                nodeColor={nodeColor}
                nodeStrokeWidth={3}
                zoomable
                pannable
                className="reactflow-minimap"
              />
              <Controls />
              <Background color={"#2F4F4F"} />
            </ReactFlow>
          </div>
        );
      case "smart-ai":
        return <AIConfiguration />;
      case "preview":
        return <WorkflowPreview />;
      default:
        return <MarkdownRenderer content={testMarkdown} className="w-full" />;
    }
  };

  return (
    <div className="flex w-full">
      <FlexLayout
        direction="row"
        gap="none"
        background="gray"
        padding="none"
        rounded="lg"
        border="default"
        className="w-full h-screen p-0"
        childrenWidths={["20%", "80%"]}
      >
        <ChatPage />

        {/* Project plan content */}
        <FlexLayout
          direction="col"
          className="h-full p-0 rounded-none bg-white w-full border-l border-gray-300 gap-0"
        >
          {/* Navbar */}
          <FlexLayout
            direction="row"
            justify="between"
            align="center"
            padding="sm"
            className="border-b bg-white w-full rounded-none"
          >
            {/* Left side - Version dropdown */}
            <FlexLayout direction="row" align="center" gap="sm">
              <Select
                value={selectedVersion}
                onChange={(value) => setSelectedVersion(value as string)}
                options={[
                  { value: "1.0", label: "Version 1.0" },
                  { value: "2.0", label: "Version 2.0" },
                ]}
                size="sm"
                variant="default"
                className="text-sm font-medium border-none"
              />
            </FlexLayout>

            {/* Center - Tabs */}
            <Tab
              items={projectTabItems}
              activeTab={activeProjectTab}
              onChange={setActiveProjectTab}
              variant="bordered"
              size="sm"
              className="w-fit"
            />

            {/* Right side - Updated text and Deploy button */}
            <FlexLayout direction="row" align="center" gap="md">
              <span className="text-sm text-gray-500">Updated 3min ago</span>
              <Button
                variant="primary"
                size="sm"
                className="bg-gray-800 hover:bg-gray-900"
              >
                Deploy
              </Button>
            </FlexLayout>
          </FlexLayout>

          {/* Rendering the tab content */}
          <div className="w-full overflow-auto p-4">{renderContent()}</div>
        </FlexLayout>
      </FlexLayout>
    </div>
  );
};

export default ProjectPlanScreen;
